# spring.application.name=hospital-eip-interactive
# camel.springboot.main-run-controller=true
# spring.main.banner-mode=off

# # No RabbitMQ and no external broker is required.
# # Apache ActiveMQ 6 runs as an embedded in-memory JMS broker for this lab.
# camel.component.activemq6.embedded=true
# camel.component.activemq6.jms-message-type=Text

spring.application.name=hospital-eip-interactive

server.port=8080

spring.web.resources.static-locations=classpath:/static/

camel.springboot.name=HospitalEIP
camel.springboot.main-run-controller=true

logging.level.org.apache.camel=INFO
logging.level.com.hospital.eip=INFO